### ISSUE TITLE
IE9 - Screens will not advance

### ISSUE THREAD

**Issue by jaredcunha** [usds/benefits-enrollment-prototype#1]
This isn't an error that will have any impact on the rails site, but it would impact testing on IE9. We can circumvent this by requiring testers to use a modern browser.  Just not sure if it's worth putting effort into this point. 

cc @mollieru

**Comment by mollieru** [comment]
This has been addressed yea?

**Comment by jaredcunha** [comment]
@mollieru - We've resolved the issue in terms of getting the demo form to advance in IE9. 

The demo uses HTML5 browser validation, which unfortunately does not work in IE9. So it possible to advance the form, and errors or missing fields could have an impact downfield. 

How we approach validation in a functioning application is worthy of another discussion, in perhaps a separate issue. My approach would be layered as follows:

1. Use HTML5 validation for modern browsers. This is the easiest implementation of validation since it requires relatively no JS, just a little to prevent Safari from submission. However, this validation functions in Chrome with no JS whatsoever. It's available to [96.91% of users (global stat)](http://caniuse.com/#search=checkValidity), optimizes performance, and includes built-in accessibility features. The alternative to would be to use a JS library that isn't predicated on `checkValidity`. However, I think in doing that, while it's possible to support IE9 and below on the client side, you lose any benefits of browsers improving their native implementation. 

2. Server-side validation. This is required, as it is primary means of preventing incorrect/missing data from going into the database. Client-side validation can fail because of errors in production or blocking third-party scripts, people can manipulate pattern criteria in the web inspector (note, this would be _highly unlikely_, though theoretically it can be done).  The reason we don't want to rely solely on server-side validation is that client-side validation is much faster and friendlier on our servers. 

Of course, the approach I've outlined will not resolve the issue of validation of IE9 in the demo, but it would resolve the issue of validation IE9 in the actual application. I'm open to other ideas, but thems my two cents.

**Comment by raquelromano** [comment]
Yep, we'll do both client- and server-side validaiton in the web application and use a polyfill on the client: https://www.html5rocks.com/en/tutorials/forms/constraintvalidation/#toc-polyfilling

We could do that here as well for anyone browsing the demo on those other browsers since there are still issues if fields are left blank. I'd say it's a nice to have for this demo.

**Comment by jaredcunha** [comment]
Ah yeah - shims!

**Comment by mollieru** [comment]
Will be resolved in https://github.com/usds/benefits-enrollment-prototype/issues/58
