### ISSUE TITLE
Zip code Format, Step 1 of 7, "Where can we send you mail?"

### ISSUE THREAD

**Issue by kathytpham** [usds/benefits-enrollment-prototype#11]
Chrome v. 54.0.2, Windows

When entering an invalid zip code, after clicking Next, a box appears that says "Please match the requested format" but does not indicate what that format is. 

![image](https://cloud.githubusercontent.com/assets/10030313/19864376/2fba929c-9f55-11e6-9aa1-178e1cc8484b.png)

**Comment by mollieru** [comment]
Will resolve in https://github.com/usds/benefits-enrollment-prototype/issues/58
