### ISSUE TITLE
Pregnancy Due Date Validation (Step 2 of 7)

### ISSUE THREAD

**Issue by kathytpham** [usds/benefits-enrollment-prototype#19]
Two issues:

No Date validation
Date can be prior to today's date

![image](https://cloud.githubusercontent.com/assets/10030313/19880001/46620820-9fb6-11e6-9ec6-1ca6a461f9f8.png)

**Comment by mollieru** [comment]
Will resolve this in https://github.com/usds/benefits-enrollment-prototype/issues/58
