### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by liyanchang** [usds/benefits-enrollment-prototype#28]
I'll let you determine priority - this seems pretty low to me.

Browser: Chrome, Safari, I presume all.

On quick-screener.html:
- You can put in letters in the zip and it will work: "121sdwd"
- The income field is not required. (Fun fact: If you put "0b1111111111111", it'll work)
- If you put letters in household size, you get "NaN people" on eligible.html
- Letters work in cooking field.

Browser: Safari
On applicant-dob-sex.html:
- If you put in a bad month, there isn't a message. 

I presume this continues for all the fields.

**Comment by mollieru** [comment]
Will resolve by work in https://github.com/usds/benefits-enrollment-prototype/issues/58
