### ISSUE TITLE
Upload and add link to research deck

### ISSUE THREAD

**Issue by mollieru** [usds/benefits-enrollment-prototype#35]

**Comment by mollieru** [comment]
@jaredcunha -- can you replace the research deck w this file? I caught a piece of content that was incomplete that I fixed...

[Discovery Findings_Mapping enrollment_Nov2016_ƒ.pdf](https://github.com/usds/benefits-enrollment-prototype/files/572357/Discovery.Findings_Mapping.enrollment_Nov2016_.pdf)

**Comment by raquelromano** [comment]
I replaced the ppt with the pdf.
