### ISSUE TITLE
Stray odd whitespace characters rendering as boxes on home page in Chrome

### ISSUE THREAD

**Issue by zerocrates** [usds/benefits-enrollment-prototype#54]
Chrome for Android example, though also visible on Chrome Linux:

![screenshot_20161102-182904](https://cloud.githubusercontent.com/assets/298975/19949873/99dc1f8e-a12a-11e6-8ff2-3970f2dfa6bd.png)

The odd characters seem to be U+2028 LINE SEPARATOR characters, though they can be hard to see because other browsers and editors don't render them or render them as whitespace, even in the source.

**Comment by jaredcunha** [comment]
@zerocrates Would you mind taking another look for me? I pushed something that _might_ have fixed it. Looks okay on a Kindle Fire, but if you were experiencing the issue, can you let me know if it still persists?

**Comment by zerocrates** [comment]
Yep, gone!

**Comment by jaredcunha** [comment]
Thank you! Closing.
